### ISSUE TITLE
Installing Ruby Gem

### ISSUE THREAD

**Issue by robertpulson** [makersacademy/unixoid-challenge#26]
I have completed the challenge, however am having trouble installing the ruby gem. 

Apparently I do not have write permission?!

**Comment by loris-fo** [comment]
Same for me, I had to use sudo.

**Comment by robertpulson** [comment]
What does that involve? Sounds like something from Breaking Bad... ;)

**Comment by loris-fo** [comment]
I don't what was the problem for you but for me it was something like this:

ERROR:     While executing gem ... (Gem: :FilePermissionError)
        You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

I recommend you to install RVM which will help you to get around this problem, but if you can't then you can use the next command to install the gem:

$ sudo gem install -unixoid-challenge

I'd use this really carefully as sudo is really powerful but if you can't submit your answers to the challenge, use it.

**Comment by spike01** [comment]
Closing this as the problem is with the underlying Ruby installation
