### ISSUE TITLE
Github repo being created but nothing being uploaded

### ISSUE THREAD

**Issue by spike01** [makersacademy/unixoid-challenge#27]
Affecting a few students - one is running Debian on Oracle on a virtual box on Windows 8 - suspect it is because Git is not installed on local machine

**Comment by spike01** [comment]
Error log:

E, [2015-01-13T10:18:18.886251 #26602] ERROR -- : Command 'git commit -m 'Unixoid submission'  2>/dev/null' returned 1. Expected 0
Here is the command output:

# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	errorlog.txt
#	logfile.log
#	my/
nothing added to commit but untracked files present (use "git add" to track)

I, [2015-01-13T10:18:18.899530 #26602]  INFO -- : 
E, [2015-01-13T10:18:27.027621 #26602] ERROR -- : Command 'git push --force -u origin master  2>/dev/null' returned 128. Expected 0
Here is the command output:


I, [2015-01-13T10:18:27.035259 #26602]  INFO -- : 

Git is working but no unixoid_results file being created

**Comment by pitchinvasion** [comment]
@spike01 did we resolve this?
