### ISSUE TITLE
Is the "checkbox" in precourse meant to automatically check?

### ISSUE THREAD

**Issue by rodcul** [makersacademy/unixoid-challenge#30]
I've uploaded my results to:

https://github.com/rodcul/unixoid_submission/blob/master/unixoid_results.txt

And I'm wondering if the checkbox in http://precourse.makersacademy.com/user/rodcul should auto check (like commits on version control challenges)

Thanks!

![precourse_makersacademy_com_user_rodcul](https://cloud.githubusercontent.com/assets/782506/6994171/84d28916-dad4-11e4-95a7-9b66d0e11106.jpg)

cc: @nikeshashar

**Comment by nikeshashar** [comment]
@rodcul This has been flagged with our engineering team. At the moment the challenge completion will not reflect on precourse.makersacademy.com - but we are working on a fix.

**Comment by spike01** [comment]
DONE DONE DONE WOOHOO
