### ISSUE TITLE
Student notification on Ronin

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/unixoid-challenge#34]
@channel - can you help UpstatePedro with this issue? 
------------------------
Unixoid-challenge completion not showing in work plan
------------------------
I completed the unixoid-challenge last night. Nikesh has confirmed that he can see this at his end. However, my "work plan" on the pre-course site is still showing this as un-ticked. 
------------------------
https://github.com/makersacademy/pre_course/issues/169

**Comment by spike01** [comment]
Closed like a baaaaaaaws
