### ISSUE TITLE
Cocaine Error on Unixoid Challenge

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/unixoid-challenge#35]
From a july pre-courser :

```/Users/Antonio/.rvm/gems/ruby-2.1.5/gems/cocaine-0.5.7/lib/cocaine/command_line.rb:83:in `run': Cocaine::CommandNotFoundError (Cocaine::CommandNotFoundError)
    from /Users/Antonio/.rvm/gems/ruby-2.1.5/gems/unixoid-challenge-0.1.3/lib/unixoid/runner.rb:21:in `run'
    from /Users/Antonio/.rvm/gems/ruby-2.1.5/gems/unixoid-challenge-0.1.3/lib/unixoid/git.rb:51:in `configured?'
    from /Users/Antonio/.rvm/gems/ruby-2.1.5/gems/unixoid-challenge-0.1.3/lib/unixoid/controller.rb:26:in `push_to_github'
    from /Users/Antonio/.rvm/gems/ruby-2.1.5/gems/unixoid-challenge-0.1.3/lib/unixoid/controller.rb:7:in `run'
    from /Users/Antonio/.rvm/gems/ruby-2.1.5/gems/unixoid-challenge-0.1.3/bin/unixoid-challenge:7:in `<top (required)>'
    from /Users/Antonio/.rvm/gems/ruby-2.1.5/bin/unixoid-challenge:23:in `load'
    from /Users/Antonio/.rvm/gems/ruby-2.1.5/bin/unixoid-challenge:23:in `<main>'
    from /Users/Antonio/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /Users/Antonio/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by roidriscoll** [comment]
Nikesh received a message saying that this error was due to the user not having git installed. Is it worth us having a check for git in the gem installation process?
