### ISSUE TITLE
wc: –l: open: No such file or directory

### ISSUE THREAD

**Issue by d9nny** [makersacademy/unixoid-challenge#40]
Hi, 

When trying to do a line count with wc -l, it keeps returning 

wc: –l: open: No such file or directory

anyone know why?

Cheers

**Comment by d9nny** [comment]
![screen shot 2015-09-20 at 09 55 08](https://cloud.githubusercontent.com/assets/14181629/9979955/ccea24f6-5f7d-11e5-9ea3-3ad029fffd36.png)

**Comment by pitchinvasion** [comment]
Hey @d9nny I don't think this is an issue with the unixoid challenge gem it looks like something that you're not doing quite right on the command line. I'm going to close this issue, I'd recommend you speak to @nikeshashar if you're stuck. Cheers :)
