### ISSUE TITLE
Q7 Not Passing, even though it has.

### ISSUE THREAD

**Issue by Adzz** [makersacademy/unixoid-challenge#41]
Question 7 wont pass but when i open a new terminal window and echo the variable it shows up like it should:

<img width="608" alt="screen shot 2015-11-01 at 11 59 42" src="https://cloud.githubusercontent.com/assets/8428277/10868763/3633cfce-8090-11e5-8804-73b2e0a7842b.png">

I'm using zsh if that affects anything?

**Comment by spike01** [comment]
Yes - the test looks in your `.bash_profile`, so if you've set it in `.zshrc` then it won't pass.
