### ISSUE TITLE
unixoid-challenge: command not found in Ubuntu 14.04

### ISSUE THREAD

**Issue by Jeremy-Barrass** [makersacademy/unixoid-challenge#43]
So, starting the challenge, install the gem, rvm tells me the gem is installed fine, but having completed the first four steps, and verified them manually, I still cannot get the command to run.

I tried passing it to ruby, then to rvm, the former giving me a no directory or file error, the latter giving me:

```sh
jeremy@jeremy-1016P:~/temp$ rvm unixoid-challenge
Warning! PATH is not properly set up, '/home/jeremy/.rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
Unknown ruby interpreter version (do not know how to handle): unixoid-challenge.
```

I've tried ``` get stable --auto-dotfiles ``` and both ``` use ruby-2.2.3 ``` and ``` ruby-2.1.2 ``` but none of these has fixed the command not found error. ``` which unixoid ``` draws a blank, if that's significant.

Can anyone tell me what path I need to add to ~/.profile to get unixoid-challenge working?

**Comment by spike01** [comment]
Have you tried just typing `unixoid-challenge`?

**Comment by Flight-of-Dragons** [comment]
Many thanks for responding, @Spike01,

Yes, I have.  That is how I know it doesn't work, because it throws the error: ``` unixoid-challenge: command not found ```.  I believe I just need to tell the shell what the file path is to get to the executable with the command, but as stated above, neither ``` which ``` nor ``` rvm ``` produce helpful results.  Possibly I need to go directory diving to find it...  I'll give ``` find ``` a go (I forget now if I've tried that or not), then manually dig through the .rvm directory for the gem and come back...

**Comment by spike01** [comment]
Thanks, that gives me a bit more context. 

Try running `rvm get stable --auto-dotfiles` and then install the gem again? If that still doesn't work, try opening up ~/.bashrc (or ~/.zshrc) and add the line: 

`export PATH="$PATH:$HOME/.rvm/bin"`

Let me know if that helps

**Comment by spike01** [comment]
You may need to open a new shell for the changes from `rvm get stable --auto-dotfiles` to take effect - or, you can type `source ~/.bash_profile`

**Comment by Flight-of-Dragons** [comment]
Hi spike01,

Alas those suggestions have not worked either.  There was a warning about using Linux in the command line tutorial, so I'm not entirely surprised the unixoid-challenege test command won't work on my system.  I've solved previous problems with a google search, but thought this one might be a bit more specialised.  I will try searching for rvm gem install problems to see if that turns up any helpful information.

**Comment by Flight-of-Dragons** [comment]
Well, I have completed all 14 tasks on the challenge, but currently have no way to test it...

Working with a fellow cohort member who can at least run the thing, but her mac may produce slightly different results to Ubuntu.

At least I have something to submit in theory.

**Comment by Jeremy-Barrass** [comment]
Well, I have the gem install as ```find .gem``` from my home directory pulls it up:

```.gem/specs/api.rubygems.org%443/quick/Marshal.4.8/unixoid-challenge-0.1.4.gemspec
```

But stll get ```unixoid-challenge: command not found``` any time I run it.

I am getting a warning:

```Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/wayneeseguin/rvm/issues/3212```

When I start a new terminal.  I am endeavouring to figure out what these should be before adding them to my ~/.profie.

**Comment by Jeremy-Barrass** [comment]
Hm...that blank space should be:
```.gem/specs/api.rubygems.org%443/quick/Marshal.4.8/unixoid-challenge-0.1.4.gemspec```

**Comment by Jeremy-Barrass** [comment]
Never mind.

**Comment by Jeremy-Barrass** [comment]
So sorting that warning: ```jeremy@jeremy-1016P:~$ echo $PATH
/home/jeremy/.rvm/gems/ruby-2.2.3/bin:/home/jeremy/.rvm/gems/ruby-2.2.3@global/bin:/home/jeremy/.rvm/rubies/ruby-2.2.3/bin:/home/jeremy/.linuxbrew/bin:/usr/local/heroku/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jeremy/Programming/Sublime/Sublime Text 2:/home/jeremy/Programming/Java/jdk1.7.0_45/bin:/home/jeremy/.rvm/bin```

The important bit being ```/home/jeremy/.rvm/gems/ruby-2.2.3/bin:/home/jeremy/.rvm/gems/ruby-2.2.3@global/bin:/home/jeremy/.rvm/rubies/ruby-2.2.3/bin```...```:/home/jeremy/.rvm/bin```

I have had ```.rvm/bin``` in my $PATH since Saturday afternoon and the unixoid-challenge command still hasn't been working.  It's past 10:00 anyway, so I guess I fail this challenge, but solving the issue will probably be wise to help with resolving command problems I may encounter in future.

With regard to the $GEM_PATH variable, I guess I should set with the ```.rvm/gem``` folders listed.  Wish me luck.

**Comment by nikeshashar** [comment]
@Jeremy-Barrass The simplest solution at the moment is not to use Linux. It's looking like something is not working and you need to be able to use RVM and install Gems for the entire PreCourse. 

This is why we recommend using c9.io instead of Linux for the PreCourse so we don't lose time in supporting different distro's. 

We can be entirely sure as to what's wrong with the machine or the install of RVM if the gem's not working properly on your system. 

I am sure our engineering team can look into it at some point but it will be well after you're past this challenge. 

Please use c9.io if gem install issues continue. 

Thanks

**Comment by Jeremy-Barrass** [comment]
Ok.  Will do so from today.  Will this challenge submission still be acceptable?

**Comment by nikeshashar** [comment]
I can take your word for it? I don't see the unxoid-submission anywhere on your github so can't verify

**Comment by Jeremy-Barrass** [comment]
There is the temp folder in my unixoid-challenge_results repo, pushed from my system where I did everything locally: https://github.com/Jeremy-Barrass/unixoid-challenge_results.  At least you can visually verify that I did something.

**Comment by nikeshashar** [comment]
Ah yes I see. That's fine
